name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Git Commit SHA and Date for Versioning
        id: version
        run: |
          VERSION_TAG="v$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          echo "Docker image version: $VERSION_TAG"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t rajeshgoyalg/python-flask-app:latest -t rajeshgoyalg/python-flask-app:${{ env.VERSION_TAG }} .

      - name: Push Docker Image
        run: |
          docker push rajeshgoyalg/python-flask-app:latest
          docker push rajeshgoyalg/python-flask-app:${{ env.VERSION_TAG }}

  update-helm:
    needs: build-test-push  # Ensures deployment happens after CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm Repository
        uses: actions/checkout@v4
        with:
          repository: rajeshgoyalg/helm-charts

      - name: Update Image Tag in values.yaml
        run: |
          sed -i "s|tag: .*|tag: ${{ env.VERSION_TAG }}|g" python-flask-app/values.yaml

      - name: Push Changes to Helm Repo
        run: |
          git config --global user.name "Rajesh Goyal"
          git config --global user.email "rajeshgoyalg@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/rajeshgoyalg/helm-charts.git
          git add python-flask-app/values.yaml
          git commit -m "Update image tag to ${{ env.VERSION_TAG }}"
          git push origin main