name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Git Commit SHA and Date for Versioning
        id: version
        run: |
          VERSION_TAG="v$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          echo "Docker image version: $VERSION_TAG"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t rajeshgoyalg/flask-app:latest -t rajeshgoyalg/flask-app:${{ env.VERSION_TAG }} .

      - name: Push Docker Image
        run: |
          docker push rajeshgoyalg/python-flask-app:latest
          docker push rajeshgoyalg/flask-app:${{ env.VERSION_TAG }}